name: flusmic_ui
description: A collection of widgets, utilities and extensions to integrate Flusmic more easy in Flutter.
version: 3.1.0
repository: https://github.com/PixelaGt/flusmic
issue_tracker: https://github.com/PixelaGt/flusmic/issues
homepage: https://github.com/PixelaGt/flusmic

publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  common_bloc:
    path: ../common_bloc

  extended_image: ^6.0.1
  flusmic: ^3.1.3

  freezed_annotation: ^1.1.0
  state_notifier: ^0.7.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.1.7
  freezed: ^1.1.1
  mocktail:
  very_good_analysis: ^2.4.0

flutter:
  #
